/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * accounting_frames.java
 *
 * Created on Oct 25, 2011, 10:36:30 PM
 */

package guiinterface;

import encryption.LedgerEncrypt;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import readwriteio.WriteChartOfAccountFile;
import javax.swing.JFrame;
/**
 *
 * @author MR
 */
public class ChartOfAccounts extends javax.swing.JPanel {

    /** Creates new form accounting_frames */
    public ChartOfAccounts() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        button5 = new java.awt.Button();
        button6 = new java.awt.Button();
        button7 = new java.awt.Button();
        button8 = new java.awt.Button();
        button9 = new java.awt.Button();
        label6 = new java.awt.Label();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList4 = new javax.swing.JList();
        jScrollPane5 = new javax.swing.JScrollPane();
        jList5 = new javax.swing.JList();
        button10 = new java.awt.Button();
        button11 = new java.awt.Button();
        button13 = new java.awt.Button();
        button14 = new java.awt.Button();
        button12 = new java.awt.Button();

        setBackground(new java.awt.Color(200, 200, 240));

        label1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label1.setFont(new java.awt.Font("Trebuchet MS", 1, 14));
        label1.setText("Assets");

        label2.setFont(new java.awt.Font("Trebuchet MS", 1, 14));
        label2.setText("Liabilities");

        label3.setFont(new java.awt.Font("Trebuchet MS", 1, 14));
        label3.setText("Owner's Equity");

        label4.setFont(new java.awt.Font("Trebuchet MS", 1, 14));
        label4.setText("Revenue");

        label5.setFont(new java.awt.Font("Trebuchet MS", 1, 14));
        label5.setText("Expenses");

        button5.setBackground(new java.awt.Color(200, 200, 240));
        button5.setFont(new java.awt.Font("Dialog", 1, 14));
        button5.setLabel("view");
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });

        button6.setBackground(new java.awt.Color(200, 200, 240));
        button6.setFont(new java.awt.Font("Dialog", 1, 14));
        button6.setLabel("create");
        button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button6ActionPerformed(evt);
            }
        });

        button7.setBackground(new java.awt.Color(200, 200, 240));
        button7.setFont(new java.awt.Font("Dialog", 1, 14));
        button7.setLabel("view");
        button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button7ActionPerformed(evt);
            }
        });

        button8.setBackground(new java.awt.Color(200, 200, 240));
        button8.setFont(new java.awt.Font("Dialog", 1, 14));
        button8.setLabel("view");
        button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button8ActionPerformed(evt);
            }
        });

        button9.setBackground(new java.awt.Color(200, 200, 240));
        button9.setFont(new java.awt.Font("Dialog", 1, 14));
        button9.setLabel("view");
        button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button9ActionPerformed(evt);
            }
        });

        label6.setAlignment(java.awt.Label.CENTER);
        label6.setFont(new java.awt.Font("Trebuchet MS", 1, 18));
        label6.setText("Chart of Accounts");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jScrollPane1.setViewportView(jList1);

        jScrollPane2.setViewportView(jList2);

        jScrollPane3.setViewportView(jList3);

        jScrollPane4.setViewportView(jList4);

        jScrollPane5.setViewportView(jList5);

        button10.setBackground(new java.awt.Color(200, 200, 240));
        button10.setFont(new java.awt.Font("Dialog", 1, 14));
        button10.setLabel("create");
        button10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button10ActionPerformed(evt);
            }
        });

        button11.setBackground(new java.awt.Color(200, 200, 240));
        button11.setFont(new java.awt.Font("Dialog", 1, 14));
        button11.setLabel("create");
        button11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button11ActionPerformed(evt);
            }
        });

        button13.setBackground(new java.awt.Color(200, 200, 240));
        button13.setFont(new java.awt.Font("Dialog", 1, 14));
        button13.setLabel("create");
        button13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button13ActionPerformed(evt);
            }
        });

        button14.setBackground(new java.awt.Color(200, 200, 240));
        button14.setFont(new java.awt.Font("Dialog", 1, 14));
        button14.setLabel("view");
        button14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button14ActionPerformed(evt);
            }
        });

        button12.setBackground(new java.awt.Color(200, 200, 240));
        button12.setFont(new java.awt.Font("Dialog", 1, 14));
        button12.setLabel("create");
        button12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(316, 316, 316)
                        .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addContainerGap()
                                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(44, 44, 44)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(button10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(button9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(20, 20, 20))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(button11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(button7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(43, 43, 43))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(40, 40, 40)
                                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(42, 42, 42)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(47, 47, 47)
                                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(69, 69, 69)
                                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(button12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(button8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(44, 44, 44)))
                                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(44, 44, 44)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(button13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(button5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGap(18, 18, 18)
                                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(47, 47, 47)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(button14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(button6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))))))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(button5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(button13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(button14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(button6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(5, 5, 5))))
                            .addComponent(jSeparator5, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE))
                        .addGap(95, 95, 95))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

private void button10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button10ActionPerformed

    if(evt.getSource()==button10)
    {
        String title="";
        try{
            while(title.equals(""))
                title=JOptionPane.showInputDialog(this, "Give the title of the new account.");
        }catch(NullPointerException e)
        {
            title="";
            JOptionPane.showMessageDialog(this, "Account not created");
        }
        if(!title.equals(""))
        {
                try {
                    WriteChartOfAccountFile.updateChartOfAccounts(title, "ASSETS", "debit");
                } catch (IOException ex) {
                    Logger.getLogger(ChartOfAccounts.class.getName()).log(Level.SEVERE, null, ex);
                } catch (Exception ex) {
                    Logger.getLogger(ChartOfAccounts.class.getName()).log(Level.SEVERE, null, ex);
                }
        }
    }
}//GEN-LAST:event_button10ActionPerformed

private void button11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button11ActionPerformed

    if(evt.getSource()==button11)
    {
        String title="";
        try{
            while(title.equals(""))
                title=JOptionPane.showInputDialog(this, "Give the title of the new account.");
        }catch(NullPointerException e)
        {
            title="";
            JOptionPane.showMessageDialog(this, "Account not created");
        }
        if(!title.equals(""))
        {
                try {
                    WriteChartOfAccountFile.updateChartOfAccounts(title, "LIABILITY", "credit");
                } catch (IOException ex) {
                    Logger.getLogger(ChartOfAccounts.class.getName()).log(Level.SEVERE, null, ex);
                } catch (Exception ex) {
                    Logger.getLogger(ChartOfAccounts.class.getName()).log(Level.SEVERE, null, ex);
                }
        }
    }
}//GEN-LAST:event_button11ActionPerformed

private void button13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button13ActionPerformed

    if(evt.getSource()==button13)
    {
        String title="";
        try{
            while(title.equals(""))
                title=JOptionPane.showInputDialog(this, "Give the title of the new account.");
        }catch(NullPointerException e)
        {
            title="";
            JOptionPane.showMessageDialog(this, "Account not created");
        }
        if(!title.equals(""))
        {
                try {
                    WriteChartOfAccountFile.updateChartOfAccounts(title, "REVENUES", "credit");
                } catch (IOException ex) {
                    Logger.getLogger(ChartOfAccounts.class.getName()).log(Level.SEVERE, null, ex);
                } catch (Exception ex) {
                    Logger.getLogger(ChartOfAccounts.class.getName()).log(Level.SEVERE, null, ex);
                }
        }
    }
}//GEN-LAST:event_button13ActionPerformed

private void button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button6ActionPerformed

    if(evt.getSource()==button6)
    {
        String title="";
        try{
            while(title.equals(""))
                title=JOptionPane.showInputDialog(this, "Give the title of the new account.");
        }catch(NullPointerException e)
        {
            title="";
            JOptionPane.showMessageDialog(this, "Account not created");
        }
        if(!title.equals(""))
        {
                try {
                    WriteChartOfAccountFile.updateChartOfAccounts(title, "EXPENSES", "debit");
                } catch (IOException ex) {
                    Logger.getLogger(ChartOfAccounts.class.getName()).log(Level.SEVERE, null, ex);
                } catch (Exception ex) {
                    Logger.getLogger(ChartOfAccounts.class.getName()).log(Level.SEVERE, null, ex);
                }
        }
    }
}//GEN-LAST:event_button6ActionPerformed

private void button12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button12ActionPerformed

    if(evt.getSource()==button12)
    {
        String title="";
        String type="";
        try{
            while(title.equals(""))
                title=JOptionPane.showInputDialog(this, "Give the title of the new account.");
            while(type.equals("") && (!type.equalsIgnoreCase("debit") || !type.equalsIgnoreCase("credit")))
                type=JOptionPane.showInputDialog(this, "Give the type of the new account. "
                        + "e.g. debit or credit");
        }catch(NullPointerException e)
        {
            title="";
            type="";
            JOptionPane.showMessageDialog(this, "Account not created");
        }
        if(!title.equals("") && !type.equals(""))
        {
                try {
                    WriteChartOfAccountFile.updateChartOfAccounts(title, "OWNERSEQUITY", type);
                } catch (IOException ex) {
                    Logger.getLogger(ChartOfAccounts.class.getName()).log(Level.SEVERE, null, ex);
                } catch (Exception ex) {
                    Logger.getLogger(ChartOfAccounts.class.getName()).log(Level.SEVERE, null, ex);
                }
        }
    }
}//GEN-LAST:event_button12ActionPerformed

private void button9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button9ActionPerformed

    if(evt.getSource()==button9)
    {
        if(jList4.getSelectedIndex()<0 || jList4.getMinSelectionIndex()<0)
        {
            JOptionPane.showMessageDialog(this, "Either no ledger is made or no ledger is selected from the list.");
        }
        else
        {
                try {
                    String b = LedgerEncrypt.encryptLedger(jList4.getSelectedValue().toString());
                    LedgerPanel one=new LedgerPanel();
                    one.setTextOfTextArea(b);

                    JFrame two=new JFrame("Ledger Account");
                    two.add(one);
                    two.setVisible(true);
                    two.setSize(500, 300);
                    two.setResizable(false);
                   // two.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(ChartOfAccounts.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(ChartOfAccounts.class.getName()).log(Level.SEVERE, null, ex);
                }
        }
    }
}//GEN-LAST:event_button9ActionPerformed

private void button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button7ActionPerformed

    if(evt.getSource()==button7)
    {
        if(jList3.getSelectedIndex()<0 || jList3.getMinSelectionIndex()<0)
        {
            JOptionPane.showMessageDialog(this, "Either no ledger is made or no ledger is selected from the list.");
        }
        else
        {
                try {
                    String b = LedgerEncrypt.encryptLedger(jList3.getSelectedValue().toString());
                    LedgerPanel one=new LedgerPanel();
                    one.setTextOfTextArea(b);

                    JFrame two=new JFrame("Ledger Account");
                    two.add(one);
                    two.setVisible(true);
                    two.setSize(500, 300);
                    two.setResizable(false);
                   // two.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(ChartOfAccounts.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(ChartOfAccounts.class.getName()).log(Level.SEVERE, null, ex);
                }
        }
    }
}//GEN-LAST:event_button7ActionPerformed

private void button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button8ActionPerformed

    if(evt.getSource()==button8)
    {
        if(jList2.getSelectedIndex()<0 || jList2.getMinSelectionIndex()<0)
        {
            JOptionPane.showMessageDialog(this, "Either no ledger is made or no ledger is selected from the list.");
        }
        else
        {
                try {
                    String b = LedgerEncrypt.encryptLedger(jList2.getSelectedValue().toString());
                    LedgerPanel one=new LedgerPanel();
                    one.setTextOfTextArea(b);

                    JFrame two=new JFrame("Ledger Account");
                    two.add(one);
                    two.setVisible(true);
                    two.setSize(500, 300);
                    two.setResizable(false);
                   // two.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(ChartOfAccounts.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(ChartOfAccounts.class.getName()).log(Level.SEVERE, null, ex);
                }
        }
    }
}//GEN-LAST:event_button8ActionPerformed

private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed

    if(evt.getSource()==button5)
    {
        if(jList5.getSelectedIndex()<0 || jList5.getMinSelectionIndex()<0)
        {
            JOptionPane.showMessageDialog(this, "Either no ledger is made or no ledger is selected from the list.");
        }
        else
        {
                try {
                    String b = LedgerEncrypt.encryptLedger(jList5.getSelectedValue().toString());
                    LedgerPanel one=new LedgerPanel();
                    one.setTextOfTextArea(b);

                    JFrame two=new JFrame("Ledger Account");
                    two.add(one);
                    two.setVisible(true);
                    two.setSize(500, 300);
                    two.setResizable(false);
                   // two.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(ChartOfAccounts.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(ChartOfAccounts.class.getName()).log(Level.SEVERE, null, ex);
                }
        }
    }
}//GEN-LAST:event_button5ActionPerformed

private void button14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button14ActionPerformed

    if(evt.getSource()==button14)
    {
        if(jList1.getSelectedIndex()<0 || jList1.getMinSelectionIndex()<0)
        {
            JOptionPane.showMessageDialog(this, "Either no ledger is made or no ledger is selected from the list.");
        }
        else
        {
                try {
                    String b = LedgerEncrypt.encryptLedger(jList1.getSelectedValue().toString());
                    LedgerPanel one=new LedgerPanel();
                    one.setTextOfTextArea(b);

                    JFrame two=new JFrame("Ledger Account");
                    two.add(one);
                    two.setVisible(true);
                    two.setSize(500, 300);
                    two.setResizable(false);
                   // two.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(ChartOfAccounts.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(ChartOfAccounts.class.getName()).log(Level.SEVERE, null, ex);
                }
        }
    }
}//GEN-LAST:event_button14ActionPerformed


    public void updateRevenueList(String  []a)
    {
        jList5.setListData(a);
    }
    
    public void updateAssetsList(String  []a)
    {
        jList4.setListData(a);
    }

     public void updateLiabilityList(String  []a)
    {
        jList3.setListData(a);
    }

    public void updateOwnersEquityList(String  []a)
    {
        jList2.setListData(a);
    }

    public void updateExpensesList(String  []a)
    {
        jList1.setListData(a);
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button10;
    private java.awt.Button button11;
    private java.awt.Button button12;
    private java.awt.Button button13;
    private java.awt.Button button14;
    private java.awt.Button button5;
    private java.awt.Button button6;
    private java.awt.Button button7;
    private java.awt.Button button8;
    private java.awt.Button button9;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JList jList3;
    private javax.swing.JList jList4;
    private javax.swing.JList jList5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    // End of variables declaration//GEN-END:variables

}
