/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * statmentDisplay.java
 *
 * Created on Oct 26, 2011, 10:53:15 PM
 */

package guiinterface;

import encryption.IncomeStatementEncrypt;
import encryption.BalanceSheet;
import encryption.OwnersEquityStatement;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author MR
 */
public class StatementDisplay extends javax.swing.JPanel {

    /** Creates new form statmentDisplay */
    public StatementDisplay() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        label1 = new java.awt.Label();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(200, 200, 240));
        setPreferredSize(new java.awt.Dimension(800, 700));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Income Statement", "Owner's Equity Statement", "Balance Sheet" }));
        jComboBox1.setInheritsPopupMenu(true);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTextPane1.setFont(new java.awt.Font("Monospaced", 0, 12));
        jTextPane1.setDisabledTextColor(new java.awt.Color(10, 10, 109));
        jTextPane1.setDoubleBuffered(true);
        jTextPane1.setEnabled(false);
        jTextPane1.setSelectionColor(new java.awt.Color(0, 0, 255));
        jScrollPane1.setViewportView(jTextPane1);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 14));
        jLabel1.setText("Statement Display");

        label1.setText("Select the Statement From the option you want to display");

        jButton1.setText("Save as External File");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(325, 325, 325)
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(70, 70, 70)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed


        if(evt.getSource()==jComboBox1)
        {
            if(jComboBox1.getSelectedIndex()==0)
                try {
                jTextPane1.setText(IncomeStatementEncrypt.getIncomeStatement());
            } catch (IOException ex) {
                Logger.getLogger(StatementDisplay.class.getName()).log(Level.SEVERE, null, ex);
            }
            if(jComboBox1.getSelectedIndex()==1)
                try {
                jTextPane1.setText(OwnersEquityStatement.getOwnersEquityStatement());
            } catch (IOException ex) {
                Logger.getLogger(StatementDisplay.class.getName()).log(Level.SEVERE, null, ex);
            }
            if(jComboBox1.getSelectedIndex()==2)
                try {
                jTextPane1.setText(BalanceSheet.getBalanceSheet());
            } catch (IOException ex) {
                Logger.getLogger(StatementDisplay.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    if(evt.getSource()==jButton1)
    {
        FileWriter resultFile=null;
        PrintWriter forResultFile=null;
        
        if(jComboBox1.getSelectedIndex()==0)
        {
            try
            {
                resultFile=new FileWriter("Income Statement.txt");
                forResultFile=new PrintWriter(resultFile);
            }catch(IOException e)
            {}
            
            ArrayList<String> read=IncomeStatementEncrypt.returnArrayListOfIncome();
            for(int i=0; i<read.size(); i++)
                forResultFile.println(read.get(i));
            
        }
        else if(jComboBox1.getSelectedIndex()==1)
        {
            try
            {
                resultFile=new FileWriter("Owners Equity Statement.txt");
                forResultFile=new PrintWriter(resultFile);
            }catch(IOException e)
            {}

            ArrayList<String> read=OwnersEquityStatement.returnArrayListOfEquity();
            for(int i=0; i<read.size(); i++)
                forResultFile.println(read.get(i));
        }
        else if(jComboBox1.getSelectedIndex()==2)
        {
            try
            {
                resultFile=new FileWriter("Balance Sheet.txt");
                forResultFile=new PrintWriter(resultFile);
            }catch(IOException e)
            {}
            
             ArrayList<String> read=BalanceSheet.returnArrayListOfBalance();
            for(int i=0; i<read.size(); i++)
                forResultFile.println(read.get(i));

        }
        forResultFile.close();
        JOptionPane.showMessageDialog(this, "It is saved as a text file in the folder where your"
                + " software is stored.");
    }
}//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables


}
