/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Transactions.java
 *
 * Created on Oct 27, 2011, 12:55:38 AM
 */

package guiinterface;

import java.awt.event.ActionEvent;
import java.awt.event.ItemListener;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import readwriteio.WriteLedgerFile;
import readwriteio.GeneralJournal;
/**
 *
 * @author MR
 */
public class Transactions extends javax.swing.JPanel {

    /** Creates new form Transactions */
    public Transactions() {
        this.setSize(800, 600);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        textField1 = new java.awt.TextField();
        label1 = new java.awt.Label();
        jSeparator1 = new javax.swing.JSeparator();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        textField2 = new java.awt.TextField();
        textField3 = new java.awt.TextField();
        textField4 = new java.awt.TextField();
        textField5 = new java.awt.TextField();
        choice1 = new java.awt.Choice();
        choice2 = new java.awt.Choice();
        choice3 = new java.awt.Choice();
        choice4 = new java.awt.Choice();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        textField6 = new java.awt.TextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(200, 200, 240));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 14));
        jLabel1.setText("Transactions");

        jLabel2.setText("Select the Account title");

        jLabel6.setText("Select the Account title");

        jLabel8.setText("Enter Amount");

        jLabel9.setText("Enter Amount");

        jButton5.setFont(new java.awt.Font("Trebuchet MS", 1, 12));
        jButton5.setText("Record Transaction");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel7.setText("Select the Account title");

        jLabel11.setText("Enter Amount");

        label1.setFont(new java.awt.Font("Trebuchet MS", 0, 12));
        label1.setText("Enter Narration");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jRadioButton3.setBackground(new java.awt.Color(200, 200, 240));
        buttonGroup3.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Trebuchet MS", 1, 12));
        jRadioButton3.setSelected(true);
        jRadioButton3.setText("Debit");
        jRadioButton3.setEnabled(false);

        jRadioButton4.setBackground(new java.awt.Color(200, 200, 240));
        buttonGroup3.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Trebuchet MS", 1, 12));
        jRadioButton4.setText("Credit");
        jRadioButton4.setEnabled(false);

        jRadioButton5.setBackground(new java.awt.Color(200, 200, 240));
        buttonGroup4.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("Trebuchet MS", 1, 12));
        jRadioButton5.setSelected(true);
        jRadioButton5.setText("Debit");
        jRadioButton5.setEnabled(false);

        jRadioButton6.setBackground(new java.awt.Color(200, 200, 240));
        buttonGroup4.add(jRadioButton6);
        jRadioButton6.setFont(new java.awt.Font("Trebuchet MS", 1, 12));
        jRadioButton6.setText("Credit");
        jRadioButton6.setEnabled(false);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel3.setText("Select the Account title");

        jLabel12.setText("Enter Amount");

        jRadioButton7.setBackground(new java.awt.Color(200, 200, 240));
        buttonGroup2.add(jRadioButton7);
        jRadioButton7.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jRadioButton7.setText("Debit");

        jRadioButton8.setBackground(new java.awt.Color(200, 200, 240));
        buttonGroup2.add(jRadioButton8);
        jRadioButton8.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jRadioButton8.setSelected(true);
        jRadioButton8.setText("Credit");

        jRadioButton9.setBackground(new java.awt.Color(200, 200, 240));
        buttonGroup1.add(jRadioButton9);
        jRadioButton9.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jRadioButton9.setSelected(true);
        jRadioButton9.setText("Debit");

        jRadioButton10.setBackground(new java.awt.Color(200, 200, 240));
        buttonGroup1.add(jRadioButton10);
        jRadioButton10.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jRadioButton10.setText("Credit");

        jCheckBox1.setBackground(new java.awt.Color(200, 200, 240));
        jCheckBox1.setText("Involve this account");
        jCheckBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox1ItemStateChanged(evt);
            }
        });

        jCheckBox2.setBackground(new java.awt.Color(200, 200, 240));
        jCheckBox2.setText("Involve this account");
        jCheckBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox2ItemStateChanged(evt);
            }
        });

        jLabel4.setText("Hint: ");

        textField2.addTextListener(new java.awt.event.TextListener() {
            public void textValueChanged(java.awt.event.TextEvent evt) {
                textField2TextValueChanged(evt);
            }
        });

        textField3.addTextListener(new java.awt.event.TextListener() {
            public void textValueChanged(java.awt.event.TextEvent evt) {
                textField3TextValueChanged(evt);
            }
        });

        textField4.setEnabled(false);
        textField4.addTextListener(new java.awt.event.TextListener() {
            public void textValueChanged(java.awt.event.TextEvent evt) {
                textField4TextValueChanged(evt);
            }
        });

        textField5.setEnabled(false);
        textField5.addTextListener(new java.awt.event.TextListener() {
            public void textValueChanged(java.awt.event.TextEvent evt) {
                textField5TextValueChanged(evt);
            }
        });

        choice3.setEnabled(false);

        choice4.setEnabled(false);

        jLabel5.setText("Month");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        jLabel10.setText("Date");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", " " }));

        jLabel13.setText("Year");

        textField6.addTextListener(new java.awt.event.TextListener() {
            public void textValueChanged(java.awt.event.TextEvent evt) {
                textField6TextValueChanged(evt);
            }
        });

        jLabel14.setText("Account 1");

        jLabel15.setText("Account 2");

        jLabel16.setText("Account 3");

        jLabel17.setText("Account 4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel14)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel8)
                                        .addComponent(jRadioButton9)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jRadioButton10)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(1, 1, 1)
                                            .addComponent(textField2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addComponent(choice1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(91, 91, 91)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel12)
                                            .addComponent(jRadioButton7))
                                        .addGap(31, 31, 31)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(choice2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jRadioButton8)
                                            .addComponent(textField3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(127, 127, 127)
                                        .addComponent(jLabel15))))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textField6, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(71, 71, 71)
                                .addComponent(jButton5))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel9)
                                            .addComponent(jRadioButton3)
                                            .addComponent(jCheckBox1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jRadioButton4)
                                                .addComponent(textField4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(choice4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(88, 88, 88)
                                        .addComponent(jLabel16)))
                                .addGap(76, 76, 76)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel11)
                                            .addComponent(jRadioButton5)
                                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(27, 27, 27)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(choice3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jRadioButton6)
                                                .addComponent(textField5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(jCheckBox2))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(choice1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(textField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRadioButton9)
                                    .addComponent(jRadioButton10)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(choice2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12)
                                    .addComponent(textField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton8)
                                    .addComponent(jRadioButton7))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7))
                            .addComponent(choice3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(choice4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9)
                                .addComponent(jLabel11))
                            .addComponent(textField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton6)
                            .addComponent(jRadioButton3)
                            .addComponent(jRadioButton4)
                            .addComponent(jRadioButton5))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBox2)
                            .addComponent(jCheckBox1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13))
                    .addComponent(textField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(398, 398, 398))
        );
    }// </editor-fold>//GEN-END:initComponents

private void textField2TextValueChanged(java.awt.event.TextEvent evt) {//GEN-FIRST:event_textField2TextValueChanged

    checkKeyTyped(textField2);
    checkValues();
}//GEN-LAST:event_textField2TextValueChanged

private void textField3TextValueChanged(java.awt.event.TextEvent evt) {//GEN-FIRST:event_textField3TextValueChanged

    checkKeyTyped(textField3);
    checkValues();
}//GEN-LAST:event_textField3TextValueChanged

private void textField4TextValueChanged(java.awt.event.TextEvent evt) {//GEN-FIRST:event_textField4TextValueChanged

    checkKeyTyped(textField4);
    checkValues();
}//GEN-LAST:event_textField4TextValueChanged

private void textField5TextValueChanged(java.awt.event.TextEvent evt) {//GEN-FIRST:event_textField5TextValueChanged

    checkKeyTyped(textField5);
    checkValues();
}//GEN-LAST:event_textField5TextValueChanged

private void boxEmpty()
{
    JOptionPane.showMessageDialog(this, "Kindly fill all the boxes.");
}

private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

    if(evt.getSource()==jButton5)
    {
        if(textField2.getText().trim().equals("") || textField3.getText().trim().equals("")
                || textField1.getText().trim().equals("") || textField6.getText().trim().equals(""))
        {
            boxEmpty();
        }
        else if(!checkValues())
        {
            JOptionPane.showMessageDialog(this, "Values do not equal. Transaction not recorded.");
        }
        else if(jCheckBox1.isSelected()==true && jCheckBox2.isSelected()==true && (textField4.getText().trim().equals("") && textField5.getText().trim().equals("")))
            boxEmpty();
        else if(jCheckBox1.isSelected()==true && textField4.getText().trim().equals(""))
            boxEmpty();
        else if(jCheckBox2.isSelected()==true && textField5.getText().trim().equals(""))
            boxEmpty();
        else
        {
            String accountTitle1="";
            String accountTitle2="";
            String accountTitle3="";
            String accountTitle4="";
            String value1="";
            String value2="";
            String value3="";
            String value4="";
            String debitOrCredit1="";
            String debitOrCredit2="";
            String debitOrCredit3="";
            String debitOrCredit4="";
            
            String date=jComboBox1.getSelectedItem() +" "+ jComboBox2.getSelectedItem() +", "
                    + textField6.getText().trim();
            String narration=textField1.getText().trim();
            
            if(jCheckBox1.isSelected()==false && jCheckBox2.isSelected()==false)
            {
                accountTitle1 = choice1.getSelectedItem();
                accountTitle2 = choice2.getSelectedItem();
                value1 = textField2.getText().trim();
                value2 = textField3.getText().trim();

                if(jRadioButton9.isSelected())
                    debitOrCredit1 = jRadioButton9.getLabel();
                else
                    debitOrCredit1 = jRadioButton10.getLabel();
                
                if(jRadioButton7.isSelected())
                    debitOrCredit2 = jRadioButton7.getLabel();
                else
                    debitOrCredit2 = jRadioButton8.getLabel();
            }
            else if(jCheckBox1.isSelected() == true && jCheckBox2.isSelected() == false)
            {
                accountTitle1 = choice1.getSelectedItem();
                accountTitle2 = choice2.getSelectedItem();
                accountTitle3 = choice4.getSelectedItem();
                value1 = textField2.getText().trim();
                value2 = textField3.getText().trim();
                value3 = textField4.getText().trim();

                if(jRadioButton9.isSelected())
                    debitOrCredit1 = jRadioButton9.getLabel();
                else
                    debitOrCredit1 = jRadioButton10.getLabel();

                if(jRadioButton7.isSelected())
                    debitOrCredit2 = jRadioButton7.getLabel();
                else
                    debitOrCredit2 = jRadioButton8.getLabel();

                if(jRadioButton3.isSelected())
                    debitOrCredit3 = jRadioButton3.getLabel();
                else
                    debitOrCredit3 = jRadioButton4.getLabel();
            }
            else if(jCheckBox2.isSelected() == true && jCheckBox1.isSelected() == false)
            {
                accountTitle1 = choice1.getSelectedItem();
                accountTitle2 = choice2.getSelectedItem();
                accountTitle4 = choice3.getSelectedItem();
                value1 = textField2.getText().trim();
                value2 = textField3.getText().trim();
                value4 = textField5.getText().trim();

                if(jRadioButton9.isSelected())
                    debitOrCredit1 = jRadioButton9.getLabel();
                else
                    debitOrCredit1 = jRadioButton10.getLabel();

                if(jRadioButton7.isSelected())
                    debitOrCredit2 = jRadioButton7.getLabel();
                else
                    debitOrCredit2 = jRadioButton8.getLabel();

                if(jRadioButton5.isSelected())
                    debitOrCredit4 = jRadioButton5.getLabel();
                else
                    debitOrCredit4 = jRadioButton6.getLabel();
            }
            else if(jCheckBox2.isSelected() == true && jCheckBox1.isSelected()== true)
            {
                accountTitle1 = choice1.getSelectedItem();
                accountTitle2 = choice2.getSelectedItem();
                accountTitle3 = choice4.getSelectedItem();
                accountTitle4 = choice3.getSelectedItem();
                value1 = textField2.getText().trim();
                value2 = textField3.getText().trim();
                value3 = textField4.getText().trim();
                value4 = textField5.getText().trim();

                if(jRadioButton9.isSelected())
                    debitOrCredit1 = jRadioButton9.getLabel();
                else
                    debitOrCredit1 = jRadioButton10.getLabel();

                if(jRadioButton7.isSelected())
                    debitOrCredit2 = jRadioButton7.getLabel();
                else
                    debitOrCredit2 = jRadioButton8.getLabel();

                if(jRadioButton5.isSelected())
                    debitOrCredit3 = jRadioButton5.getLabel();
                else
                    debitOrCredit3 = jRadioButton6.getLabel();

                if(jRadioButton3.isSelected())
                    debitOrCredit4 = jRadioButton3.getLabel();
                else
                    debitOrCredit4 = jRadioButton4.getLabel();
            }
            
            System.out.println(value1 +" "+ value2 +" "+ value3 +" "+ value4);
            System.out.println(accountTitle1 +" "+ accountTitle2 +" "+ accountTitle3 +" "+ accountTitle4);
            System.out.println(debitOrCredit1 +" "+ debitOrCredit2 +" "+ debitOrCredit3 +" "+ debitOrCredit4);
            
            /* journal
            String info1="";
            String info2="";
             */
            try {
                    WriteLedgerFile.writeLedgerAndReturnInfo(accountTitle1, date, value1, narration, debitOrCredit1);
                } catch (IOException ex) {
                    Logger.getLogger(Transactions.class.getName()).log(Level.SEVERE, null, ex);
                }
            try {
                    WriteLedgerFile.writeLedgerAndReturnInfo(accountTitle2, date, value2, narration, debitOrCredit2);
                } catch (IOException ex) {
                    Logger.getLogger(Transactions.class.getName()).log(Level.SEVERE, null, ex);
                }
            
            /* Journal
            String accountsWithValues1=accountTitle1+"//";
            accountsWithValues1 += WriteLedgerFile.valueNegativeOrPositive(info1, value1, debitOrCredit1);
            
            String accountsWithValues2 =accountTitle2+"//";
            accountsWithValues2 += WriteLedgerFile.valueNegativeOrPositive(info2, value2, debitOrCredit2);
            
            String accountsWithValues3 = "";
            
            String accountsWithValues4 = "";
            */
            
            if(jCheckBox1.isSelected())
            {
               // String info="";
                try {
                    WriteLedgerFile.writeLedgerAndReturnInfo(accountTitle3, date, value3, narration, debitOrCredit3);
                } catch (IOException ex) {
                    Logger.getLogger(Transactions.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                /**
                accountsWithValues3 =accountTitle3+"//";
                accountsWithValues3 += WriteLedgerFile.valueNegativeOrPositive(info, value3, debitOrCredit3);*/
            }
            
            if(jCheckBox2.isSelected())
            {
                // String info="";
                try {
                    WriteLedgerFile.writeLedgerAndReturnInfo(accountTitle4, date, value4, narration, debitOrCredit4);
                } catch (IOException ex) {
                    Logger.getLogger(Transactions.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                /** journal
                accountsWithValues4 +=accountTitle4+"//";
                accountsWithValues4 += WriteLedgerFile.valueNegativeOrPositive(info, value4, debitOrCredit4);*/
            }
            
            
       /**     Journal
            try {
                GeneralJournal.updateJournal(date, accountsWithValues1, accountsWithValues2,
                        accountsWithValues3, accountsWithValues4, narration);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Transactions.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Transactions.class.getName()).log(Level.SEVERE, null, ex);
            }
            */
            JOptionPane.showMessageDialog(this, "Your transaction has been recorded.");
        }
    }
}//GEN-LAST:event_jButton5ActionPerformed

private void textField6TextValueChanged(java.awt.event.TextEvent evt) {//GEN-FIRST:event_textField6TextValueChanged
    
    checkKeyTyped(textField6);
}//GEN-LAST:event_textField6TextValueChanged

private void jCheckBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox2ItemStateChanged
    if(jCheckBox2.isSelected()==true) {
        choice3.setEnabled(true);
        textField5.setEditable(true);
        textField5.setEnabled(true);
        jRadioButton5.setEnabled(true);
        jRadioButton6.setEnabled(true);
        checkValues();
    }
    if(jCheckBox2.isSelected()==false) {
        choice3.setEnabled(false);
        textField5.setEditable(false);
        textField5.setEnabled(false);
        jRadioButton5.setEnabled(false);
        jRadioButton6.setEnabled(false);
        checkValues();
    }
}//GEN-LAST:event_jCheckBox2ItemStateChanged

private void jCheckBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox1ItemStateChanged
    if(jCheckBox1.isSelected()==true) {
        choice4.setEnabled(true);
        textField4.setEditable(true);
        textField4.setEnabled(true);
        jRadioButton3.setEnabled(true);
        jRadioButton4.setEnabled(true);
        checkValues();
    }
    if(jCheckBox1.isSelected()==false) {
        choice4.setEnabled(false);
        textField4.setEditable(false);
        textField4.setEnabled(false);
        jRadioButton3.setEnabled(false);
        jRadioButton4.setEnabled(false);
        checkValues();
    }
}//GEN-LAST:event_jCheckBox1ItemStateChanged

private void valuesNotEqual()
{
    jButton5.setEnabled(false);
    jLabel4.setText("Hint: Values does not equal. There will be ineqaulity in Trial"
        + " Balance");
}

private void valuesEqual()
{
    jButton5.setEnabled(true);
    jLabel4.setText("Hint: You can record the transaction if you have defined all"
            + " the corresponding accounts");
}

private Boolean checkValues() throws java.lang.NumberFormatException
{
    try{
    if(!jCheckBox1.isSelected() && !jCheckBox2.isSelected())
    {
        if(textField3.getText()!=null)
        {
            if(Integer.parseInt(textField2.getText().trim())!=Integer.parseInt(textField3.getText().trim()))
            {
                valuesNotEqual();
                return false;
            }
            else
            {
                valuesEqual();
                return true;
            }
        }
    }
    if(jCheckBox1.isSelected())
    {
        if(textField3.getText()!=null || textField4.getText()!=null)
        {
            int valueOfTextBox1 = Integer.parseInt(textField2.getText().trim());
            int valueOfTextBox2 = Integer.parseInt(textField3.getText().trim());
            int valueOfTextBox3 = Integer.parseInt(textField4.getText().trim());
            
            if(valueOfTextBox1!=valueOfTextBox2+valueOfTextBox3)
            {
                valuesNotEqual();
                return false;
            }
            else
            {
                valuesEqual();
                return true;
            }
        }
    }
    
    if(jCheckBox2.isSelected())
    {
        if(textField3.getText()!=null || textField5.getText()!=null)
        {
            int valueOfTextBox1 = Integer.parseInt(textField2.getText().trim());
            int valueOfTextBox2 = Integer.parseInt(textField3.getText().trim());
            int valueOfTextBox3 = Integer.parseInt(textField5.getText().trim());
            
            if(valueOfTextBox1!=valueOfTextBox2+valueOfTextBox3)
            {
                valuesNotEqual();
                return false;
            }
            else
            {
                valuesEqual();
                return true;
            }
        }
    }
    
    if(jCheckBox2.isSelected() && jCheckBox1.isSelected())
    {
        if(textField3.getText()!=null || textField4.getText()!=null || textField5.getText()!=null)
        {
            int valueOfTextBox1 = Integer.parseInt(textField2.getText().trim());
            int valueOfTextBox2 = Integer.parseInt(textField3.getText().trim());
            int valueOfTextBox3 = Integer.parseInt(textField4.getText().trim());
            int valueOfTextBox4 = Integer.parseInt(textField5.getText().trim());
            
            if(valueOfTextBox1!=valueOfTextBox2+valueOfTextBox3+valueOfTextBox4)
            {
                valuesNotEqual();
                return false;
            }
            else
            {
                valuesEqual();
                return true;
            }
        }
    }
    }catch(NumberFormatException e)
    {}
    return false;
}

private void checkKeyTyped(java.awt.TextField b)
{
   if(hasLetter(b))
    {
        jButton5.setEnabled(false);
        jLabel4.setText("Hint: Value must be a number.");
    }
    else
    {
        jButton5.setEnabled(true);
        jLabel4.setText("Hint: You can record the transaction if you have defined all"
            + " the corresponding accounts");
    }
}
private boolean hasLetter(java.awt.TextField b) throws java.lang.NumberFormatException
{
    for(int i=0; i<b.getText().length(); i++)
        if(!Character.isDigit(b.getText().trim().charAt(i)))
            return true;
    return false;
}


public void updateChoice(String []a, String []b, String []c, String []d, String []e)
{
    choice1.removeAll();
    choice2.removeAll();
    choice3.removeAll();
    choice4.removeAll();
    
    for (int i=0; i<a.length; i++)
    {
        choice1.add(a[i]);
        choice2.add(a[i]);
        choice3.add(a[i]);
        choice4.add(a[i]);
    }

    for (int i=0; i<b.length; i++)
    {
        choice1.add(b[i]);
        choice2.add(b[i]);
        choice3.add(b[i]);
        choice4.add(b[i]);
    }

    for (int i=0; i<c.length; i++)
    {
        choice1.add(c[i]);
        choice2.add(c[i]);
        choice3.add(c[i]);
        choice4.add(c[i]);
    }

    for (int i=0; i<d.length; i++)
    {
        choice1.add(d[i]);
        choice2.add(d[i]);
        choice3.add(d[i]);
        choice4.add(d[i]);
    }

    for (int i=0; i<e.length; i++)
    {
        choice1.add(e[i]);
        choice2.add(e[i]);
        choice3.add(e[i]);
        choice4.add(e[i]);
    }
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private java.awt.Choice choice1;
    private java.awt.Choice choice2;
    private java.awt.Choice choice3;
    private java.awt.Choice choice4;
    private javax.swing.JButton jButton5;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private java.awt.Label label1;
    private java.awt.TextField textField1;
    private java.awt.TextField textField2;
    private java.awt.TextField textField3;
    private java.awt.TextField textField4;
    private java.awt.TextField textField5;
    private java.awt.TextField textField6;
    // End of variables declaration//GEN-END:variables


}










